### ISSUE TITLE
Issue with the tutorial and the running of the simulation

### ISSUE THREAD

**Issue by bboyeleven** [UM-PEPL/HallThruster.jl#135]
Hi, I’m currently learning and using the package HallThruster.jl.
At first running of the code available in the tutorial on my cmd (https://um-pepl.github.io/HallThruster.jl/dev/run/) everything was fine and I was getting the same results as in the tutorial. But now (3 days later) I wanted to try again but the graphics obtained are not the right ones and every of my simulation isn’t working as planned (the thrust for example is not zero for only the 1st element of the spatial discretization).

I don't know if the problem come from the code but may be from some wrong command entered in Julia or a background simulation still running.

Any ideas are welcome thx.
Here are the plots that I got :
![Capture d'écran 2024-06-11 181216](https://github.com/UM-PEPL/HallThruster.jl/assets/172601348/a3c1ab8e-f3ec-429b-bb40-c6adf998a19f)

**Comment by archermarx** [comment]
Hey thanks for reaching out. The tutorial is a bit out of date and needs to
be redone. I'll see if I can get a new version out today.

**Comment by bboyeleven** [comment]
Thanks it would be a great help. Have you ever encountered that kind of problem before ?

**Comment by archermarx** [comment]
I found a bug that had affected the tutorial. If you update HallThruster.jl to version 14.3 (should be tagged within the hour)  the bug should be fixed. I've also updated the tutorial so that it should work with the current version!

**Comment by bboyeleven** [comment]
Ok, thanks a lot ! I'll see if the problem is resolved by updating and re-launch my code.
By curiosity what was the bug that you found ?

**Comment by archermarx** [comment]
Great to hear! The problem had to do with a change I made to store `ncells` in the `params` struct. In `run_simulation`, you can either specify an `ncells`, in which case an `EvenGrid` is constructed, or explicitly pass in a grid. I had handled the latter case but not the former, resulting in `ncells` being left at zero in the params struct.
