### ISSUE TITLE
'params' not defined UndefVarError when passing solution into plot()

### ISSUE THREAD

**Issue by hmalik-p4** [UM-PEPL/HallThruster.jl#141]
Hi, very new to Julia so please bear with me if this is off base. I'm getting an `UndefVarError: 'params' not defined` when trying to pass my Solution object into the plot() function to use the built in plotting recipes.

```
my_solution = HallThruster.run_simulation(my_config; ncells = 100, nsave=10000, dt=1e-8, duration=1e-3)

plot(my_solution)
```
The stack trace points to line 3 of recipes.jl in the visualization folder.

Any thoughts on if this is a bug or I'm just doing something wrong? Many thanks!

**Comment by archermarx** [comment]
That's weird. Can you post a full minimum working example? Nothing complicated, just show how you define my_config? Also, what happens if you  type `my_solution.params`?

**Comment by hmalik-p4** [comment]
```
using HallThruster, Unitful, Plots

my_geometry = HallThruster.Geometry1D(
    channel_length = xxx,  
    inner_radius = xxx,
    outer_radius = xxx
)


function my_magnetic_field(z)
    if z < x
        xx
    else
        xx
    end
end

my_thruster = HallThruster.Thruster(
	name = "xxx",
    magnetic_field = my_magnetic_field,
    geometry = my_geometry,
    shielded = true,
)

my_config = HallThruster.Config(
    ncharge = 2,
    discharge_voltage = 300u"V",
    thruster = my_thruster,
    domain = (0.0u"cm", 8.0u"cm"),
    anode_mass_flow_rate = 2.0u"mg/s",
    wall_loss_model = HallThruster.WallSheath(HallThruster.BoronNitride),
    anom_model = HallThruster.MultiLogBohm([0.02, 0.03, 0.04, 0.06, 0.006, 0.2]),
    propellant = Xenon,
    neutral_velocity = 500.0u"m/s",
    neutral_temperature = 500.0u"K",
    ion_temperature = 500.0u"K",
    cathode_Te = 2.5u"eV",
    anode_Te = 2.5u"eV",
    ion_wall_losses = true,
)

my_solution = HallThruster.run_simulation(my_config; ncells = 100, nsave=10000, dt=1e-8, duration=1e-3)

println(my_solution.params)
plot(my_solution)
```

I've redacted/generalized some information but otherwise kept everything the same. Printing the params field spits out a tuple with all of the parameters in it, but the same UndefVarError shows up when passing my_solution into the plot function

**Comment by archermarx** [comment]
Huh, that's super weird. I'll look into this.

**Comment by archermarx** [comment]
Ok, I think it should be fixed

**Comment by hmalik-p4** [comment]
Confirming that it's fixed! Plot recipe working as expected

**Comment by hmalik-p4** [comment]
Confirming that it's fixed! Plot recipe working as expected
