### ISSUE TITLE
Config  Struct

### ISSUE THREAD

**Issue by dynamic-queries** [UM-PEPL/HallThruster.jl#78]
It might be  convenient to subsume the parameters of  the Config Struct : 
- Simulation parameters -> Simulation_Struct
- Model_parameters -> Model_Struct

And store these two sub-structs in config. Thoughts ?

**Comment by archermarx** [comment]
Yes, that could work. We'd want to keep a convenience constructor though

**Comment by archermarx** [comment]
Reopening until we get a PR to do this

**Comment by dynamic-queries** [comment]
I'll open a PR today.

**Comment by archermarx** [comment]
Closing for now
