### ISSUE TITLE
Steady State solution

### ISSUE THREAD

**Issue by dynamic-queries** [UM-PEPL/HallThruster.jl#79]
The Steady State solution for update_heavy_species! does not converge with the SciML Nonlinear Solvers.

I setup the parameters similar to the run_simulation function for LANDMARK 1,2,3  and define the Nonlinear problem as such.
`prob = ODEProblem(HT.update_heavy_species!, U, tspan, params)`

Using the nice Non-linear solver interface from SciML and its auto-solver selection feature, one can write:
`nl_prob = NonlinearProblem(prob)`
`solution = solve(nl_prob)`

Note, I tried this with other solvers such as NetwonRaphson(autodiff=false), CVODE_BDF() and solutions from all of them diverge. 

Is there a way to explain this behaviour ?

**Comment by archermarx** [comment]
Hall thrusters are unsteady inherently so I'm not sure I would expect
steady solvers to work. Also, any Newton Raphson scheme would employ
autodiff and the code isn't yet built to work with it

**Comment by archermarx** [comment]
I would also make sure you have a sensible initial condition, maybe prescribe a gaussian electron temperature to start. Are you using the initialization code?

**Comment by dynamic-queries** [comment]
> Hall thrusters are unsteady inherently so I'm not sure I would expect steady solvers to work. Also, any Newton Raphson scheme would employ autodiff and the code isn't yet built to work with it

You're right! You could compute derivatives numerically though. The question of its accuracy (blow up) is another matter.

**Comment by dynamic-queries** [comment]
Yes, the one from the LANDMARK case.

**Comment by archermarx** [comment]
I forget whether you can use finite diff with these solvers. Have you tried that? A pseudo-steady solver would be a great addition to the code. Many previous 1D codes have been steady, but we didn't build this code with that in mind.

**Comment by dynamic-queries** [comment]
I have. This is the case that diverges.

**Comment by archermarx** [comment]
OK, I'll think about this some. I will be busy tomorrow until about this time and then I can take a look. Can you paste your code here so I can try and reproduce?

**Comment by dynamic-queries** [comment]
Sure! 
On the question on unstability of Hall Thrusters, I remember a paper(that I cannot find at the moment) from LAPLACE that analyzes the steady state behaviour of fluid equations. I was simply trying to emulate that idea.

EItherway, I will open a PR with my code in it. We could continue this discussion there.

**Comment by dynamic-queries** [comment]
>> Many previous 1D codes have been steady, but we didn't build this code with that in mind 

Could you give an example of one that was?

**Comment by archermarx** [comment]
Here's a good one

https://www.researchgate.net/publication/234879884_One-dimensional_model_of_the_plasma_flow_in_a_Hall_thruster

**Comment by dynamic-queries** [comment]
using HallThruster
using Plots
using NonlinearSolve

function run_landmark(duration = 1e-3; ncells = 200, nsave = 2, dt = 0.7e-8, case = 1)

domain = (0.0, 0.05)

#Landmark cases loss frequencies
αϵ_in, αϵ_out = if case == 1
    (1.0, 1.0)
elseif case == 2
    (0.5, 1.0)
elseif case == 3
    (0.4, 1.0)
end

scheme = HallThruster.HyperbolicScheme(flux_function = HallThruster.global_lax_friedrichs, limiter = HallThruster.van_leer, reconstruct = true)

ϵ_anode = 3.0
ϵ_cathode = 3.0

transition_function = HallThruster.LinearTransition(1e-3, 0.0)

config = HallThruster.Config(;
    ncharge = 1,
    anode_Te = 2/3 * ϵ_anode,
    cathode_Te = 2/3 * ϵ_cathode,
    discharge_voltage = 300.0,
    ionization_model = HallThruster.LandmarkIonizationLookup(),
    excitation_model = HallThruster.LandmarkExcitationLookup(),
    electron_neutral_model = HallThruster.LandmarkElectronNeutral(),
    electron_ion_collisions = false,
    wall_loss_model = HallThruster.ConstantSheathPotential(20, αϵ_in, αϵ_out),
    LANDMARK = true,
    neutral_velocity = 150.0,
    neutral_temperature = 0.0,
    ion_temperature = 0.0,
    thruster = HallThruster.SPT_100,
    anode_mass_flow_rate = 5e-6,
    scheme,
    domain,
    transition_function,
    electron_pressure_coupled = true,
    ion_wall_losses = false,
)

@time prob,sol = HallThruster.run_simulation(config; dt, duration, ncells, nsave)
return prob,sol
end

prob,sol = run_landmark()
p = prob.params
function f(U,params)
dU = zero(U)
prob.f(dU,U,p,0.0)
dU
end 

nl_prob = NonlinearProblem(f,prob.u)
solve(nl_prob,NewtonRaphson(autodiff=false))

**Comment by dynamic-queries** [comment]
In the code above, I slightly modify the run simulation to return the ODEProblem struct.
Then I setup the Non-linear solver which returns a singular exception.
